"""
upload/health/constants.py
~~~~~~~~~~~~~~~~~~~~~~~~~~
Lookup tables for Health Auto Export metric handling.

METRIC_AGGREGATION: maps display metric name → sub-metric → aggregation type.
  Used by _get_agg_type() to decide how to combine multiple readings within
  an INTERVAL_MINUTES bucket (sum, mean, min, max).

METRICS: master list of all HAE metric names (used for gap-checking).

SNAKE_TO_DISPLAY: maps snake_case HAE export name → display metric name.
  Needed because HAE sends metrics with underscored names but the DB stores
  the human-readable display name (e.g. "heart_rate" → "Heart Rate").
"""

METRIC_AGGREGATION = {
    "Active Energy": {"Active Energy (kJ)": "sum"},
    "Apple Exercise Time": {"Apple Exercise Time (min)": "sum"},
    "Apple Stand Hour": {"Apple Stand Hour (count)": "sum"},
    "Apple Stand Time": {"Apple Stand Time (min)": "sum"},
    "Blood Oxygen Saturation": {"Blood Oxygen Saturation (%)": "mean"},
    "Environmental Audio Exposure": {"Environmental Audio Exposure (dBASPL)": "mean"},
    "Flights Climbed": {"Flights Climbed (count)": "sum"},
    "Heart Rate Variability": {"Heart Rate Variability (ms)": "mean"},
    "Heart Rate": {"Min (count/min)": "min", "Avg (count/min)": "mean", "Max (count/min)": "max"},
    "Physical Effort": {"Physical Effort (kcal/hr·kg)": "sum"},
    "Resting Energy": {"Resting Energy (kJ)": "sum"},
    "Resting Heart Rate": {"Resting Heart Rate (count/min)": "mean"},
    "Sleep Analysis": {"Sleep Analysis (min)": "sum"},
    "Stair Speed: Down": {"Stair Speed: Down (m/s)": "mean"},
    "Stair Speed: Up": {"Stair Speed: Up (m/s)": "mean"},
    "Step Count": {"Step Count (count)": "sum"},
    "Walking + Running Distance": {"Walking + Running Distance (km)": "sum"},
    "Walking Asymmetry Percentage": {"Walking Asymmetry Percentage (%)": "mean"},
    "Walking Double Support Percentage": {"Walking Double Support Percentage (%)": "mean"},
    "Walking Heart Rate Average": {"Walking Heart Rate Average (count/min)": "mean"},
    "Walking Speed": {"Walking Speed (km/hr)": "mean"},
    "Walking Step Length": {"Walking Step Length (cm)": "mean"},
}

METRICS = [
    "Active Energy",
    "Alcohol Consumption",
    "Apple Exercise Time",
    "Apple Move Time",
    "Apple Sleeping Wrist Temperature",
    "Apple Stand Hour",
    "Apple Stand Time",
    "Atrial Fibrillation Burden",
    "Basal Body Temperature",
    "Basal Energy Burned",
    "Biotin",
    "Blood Alcohol Content",
    "Blood Glu",
    "Blood Oxygen Saturation",
    "Blood Pres",
    "Body Fat Percentage",
    "Body Mass Index",
    "Breathing Disturbances",
    "Caffeine",
    "Calcium",
    "Carbohydrates",
    "Cardio Recovery",
    "Chloride",
    "Cholesterol",
    "Chromium",
    "Copper",
    "Cycling Cadence",
    "Cycling Distance",
    "Cycling Functional Threshold Power",
    "Cycling Power",
    "Cycling Speed",
    "Dietary Energy",
    "Distance Downhill Snow Sports",
    "Electrodermal Activity",
    "Environmental Audio Exposure",
    "Fiber",
    "Flights Climbed",
    "Fola",
    "Forced Expiratory Volume 1",
    "Forced Vital Capacity",
    "Handwashing",
    "Headphone Audio Exposure",
    "Heart Rate Variability",
    "Height",
    "Inhaler Usage",
    "Insulin Delivery",
    "Iodine",
    "Iron",
    "Lean Body Mas",
    "Magnesium",
    "Manganese",
    "Mindful Minutes",
    "Molybdenum",
    "Monounsaturated Fat",
    "Niacin",
    "Number of Times Fallen",
    "Pantothenic Acid",
    "Peak Expiratory Flow Rate",
    "Peripheral Perfusion Index",
    "Phosphorus",
    "Physical Effort",
    "Polyunsaturated Fat",
    "Potassium",
    "Protein",
    "Push Count",
    "Respiratory Rate",
    "Resting Energy",
    "Resting Heart Rate",
    "Riboflavin",
    "Running Ground Contact Time",
    "Running Power",
    "Running Speed",
    "Running Stride Length",
    "Running Vertical Oscillation",
    "Saturated Fat",
    "Selenium",
    "Sexual Activity",
    "Six-Minute Walking Test Distance",
    "Sleep Analysis",
    "Sodium",
    "Stair Speed: Down",
    "Stair Speed: Up",
    "Step Count",
    "Sugar",
    "Swimming Distance",
    "Swimming Stroke Count",
    "Thiamin",
    "Time in Daylight",
    "Toothbrushing",
    "Total Fat",
    "UV Exposure",
    "Underwater Depth",
    "Underwater Temperature",
    "VO2 Max",
    "Vitamin A",
    "Vitamin B12",
    "Vitamin B6",
    "Vitamin C",
    "Vitamin D",
    "Vitamin E",
    "Vitamin K",
    "Waist Circumference",
    "Walking + Running Distance",
    "Walking Asymmetry Percentage",
    "Walking Double Support Percentage",
    "Walking Heart Rate Average",
    "Walking Speed",
    "Walking Step Length",
    "Water",
    "Weight",
    "Wheelchair Distance",
    "Zinc",
]

SNAKE_TO_DISPLAY = {
    "active_energy": "Active Energy",
    "alcohol_consumption": "Alcohol Consumption",
    "apple_exercise_time": "Apple Exercise Time",
    "apple_move_time": "Apple Move Time",
    "apple_sleeping_wrist_temperature": "Apple Sleeping Wrist Temperature",
    "apple_stand_hour": "Apple Stand Hour",
    "apple_stand_time": "Apple Stand Time",
    "atrial_fibrillation_burden": "Atrial Fibrillation Burden",
    "basal_body_temperature": "Basal Body Temperature",
    "basal_energy_burned": "Basal Energy Burned",
    "biotin": "Biotin",
    "blood_alcohol_content": "Blood Alcohol Content",
    "blood_glucose": "Blood Glu",
    "blood_oxygen_saturation": "Blood Oxygen Saturation",
    "blood_pressure": "Blood Pres",
    "body_fat_percentage": "Body Fat Percentage",
    "body_mass_index": "Body Mass Index",
    "breathing_disturbances": "Breathing Disturbances",
    "caffeine": "Caffeine",
    "calcium": "Calcium",
    "carbohydrates": "Carbohydrates",
    "cardio_recovery": "Cardio Recovery",
    "chloride": "Chloride",
    "cholesterol": "Cholesterol",
    "chromium": "Chromium",
    "copper": "Copper",
    "cycling_cadence": "Cycling Cadence",
    "cycling_distance": "Cycling Distance",
    "cycling_functional_threshold_power": "Cycling Functional Threshold Power",
    "cycling_power": "Cycling Power",
    "cycling_speed": "Cycling Speed",
    "dietary_energy": "Dietary Energy",
    "distance_downhill_snow_sports": "Distance Downhill Snow Sports",
    "electrodermal_activity": "Electrodermal Activity",
    "environmental_audio_exposure": "Environmental Audio Exposure",
    "fiber": "Fiber",
    "flights_climbed": "Flights Climbed",
    "folate": "Fola",
    "forced_expiratory_volume_1": "Forced Expiratory Volume 1",
    "forced_vital_capacity": "Forced Vital Capacity",
    "handwashing": "Handwashing",
    "headphone_audio_exposure": "Headphone Audio Exposure",
    "heart_rate_variability": "Heart Rate Variability",
    "heart_rate": "Heart Rate",
    "height": "Height",
    "inhaler_usage": "Inhaler Usage",
    "insulin_delivery": "Insulin Delivery",
    "iodine": "Iodine",
    "iron": "Iron",
    "lean_body_mass": "Lean Body Mas",
    "magnesium": "Magnesium",
    "manganese": "Manganese",
    "mindful_minutes": "Mindful Minutes",
    "molybdenum": "Molybdenum",
    "monounsaturated_fat": "Monounsaturated Fat",
    "niacin": "Niacin",
    "number_of_times_fallen": "Number of Times Fallen",
    "pantothenic_acid": "Pantothenic Acid",
    "peak_expiratory_flow_rate": "Peak Expiratory Flow Rate",
    "peripheral_perfusion_index": "Peripheral Perfusion Index",
    "phosphorus": "Phosphorus",
    "physical_effort": "Physical Effort",
    "polyunsaturated_fat": "Polyunsaturated Fat",
    "potassium": "Potassium",
    "protein": "Protein",
    "push_count": "Push Count",
    "respiratory_rate": "Respiratory Rate",
    "resting_energy": "Resting Energy",
    "resting_heart_rate": "Resting Heart Rate",
    "riboflavin": "Riboflavin",
    "running_ground_contact_time": "Running Ground Contact Time",
    "running_power": "Running Power",
    "running_speed": "Running Speed",
    "running_stride_length": "Running Stride Length",
    "running_vertical_oscillation": "Running Vertical Oscillation",
    "saturated_fat": "Saturated Fat",
    "selenium": "Selenium",
    "sexual_activity": "Sexual Activity",
    "six_minute_walking_test_distance": "Six-Minute Walking Test Distance",
    "sleep_analysis": "Sleep Analysis",
    "sodium": "Sodium",
    "stair_speed_down": "Stair Speed: Down",
    "stair_speed_up": "Stair Speed: Up",
    "step_count": "Step Count",
    "sugar": "Sugar",
    "swimming_distance": "Swimming Distance",
    "swimming_stroke_count": "Swimming Stroke Count",
    "thiamin": "Thiamin",
    "time_in_daylight": "Time in Daylight",
    "toothbrushing": "Toothbrushing",
    "total_fat": "Total Fat",
    "uv_exposure": "UV Exposure",
    "underwater_depth": "Underwater Depth",
    "underwater_temperature": "Underwater Temperature",
    "vo2_max": "VO2 Max",
    "vitamin_a": "Vitamin A",
    "vitamin_b12": "Vitamin B12",
    "vitamin_b6": "Vitamin B6",
    "vitamin_c": "Vitamin C",
    "vitamin_d": "Vitamin D",
    "vitamin_e": "Vitamin E",
    "vitamin_k": "Vitamin K",
    "waist_circumference": "Waist Circumference",
    "walking_running_distance": "Walking + Running Distance",
    "walking_asymmetry_percentage": "Walking Asymmetry Percentage",
    "walking_double_support_percentage": "Walking Double Support Percentage",
    "walking_heart_rate_average": "Walking Heart Rate Average",
    "walking_speed": "Walking Speed",
    "walking_step_length": "Walking Step Length",
    "water": "Water",
    "weight_body_mass": "Weight",
    "wheelchair_distance": "Wheelchair Distance",
    "zinc": "Zinc",
}
